title: A Updating Collection of Healthcare Large Langauge Models
description: We create an overview of advanced LLM applications that are leveraged in healthcare, medicine and clinical settings.
remote_theme: pages-themes/hacker@v0.2.0
show_downloads: "true"
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
